# Generated by Django 4.1 on 2022-09-26 13:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='My_score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(default='player_id', max_length=10)),
                ('myscr', models.IntegerField(default=0)),
                ('season_gameid', models.CharField(default='gameid', max_length=10)),
                ('total_score', models.IntegerField(default=0)),
                ('played_dt', models.DateField(verbose_name=datetime.date(2022, 9, 26))),
                ('player_groupid', models.CharField(default='group_id', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='P_score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerScoreDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField()),
                ('seasonGame_id', models.CharField(max_length=30)),
                ('obtained_marks', models.IntegerField()),
                ('total_marks', models.IntegerField()),
                ('group_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz_up',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Match', models.CharField(max_length=250)),
                ('Questions', models.CharField(max_length=250)),
                ('option_A', models.CharField(max_length=250)),
                ('option_B', models.CharField(max_length=250)),
                ('option_C', models.CharField(max_length=250)),
                ('option_D', models.CharField(max_length=250)),
                ('Right_Answer', models.CharField(max_length=250)),
                ('quiz_fact', models.CharField(max_length=250)),
                ('image', models.ImageField(default='logo.png', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='user_stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(max_length=10)),
                ('alloted_qid', models.CharField(max_length=100)),
                ('groupid', models.CharField(max_length=10)),
                ('gameid', models.CharField(max_length=10)),
                ('user_days_score', models.IntegerField(default=10)),
                ('user_total_score', models.IntegerField(default=0)),
                ('marks_of_days_quiz', models.IntegerField(default=0)),
                ('total_marks_of_quiz', models.IntegerField(default=0)),
                ('accuracy', models.IntegerField(default=0)),
                ('total_days_participated', models.IntegerField(default=0)),
                ('consecutive_streak', models.IntegerField(default=0)),
                ('streak_counter', models.IntegerField(default=0)),
                ('date_of_participation', models.DateField(default=datetime.date(2022, 9, 26))),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Player_name', models.CharField(default='guest', max_length=100)),
                ('day_score', models.IntegerField(default=0)),
                ('attemt', models.IntegerField(default=0)),
                ('season_score', models.IntegerField(default=0)),
                ('attended', models.BooleanField(default=False)),
                ('accuracy', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=0)),
                ('percentile', models.FloatField(default=0)),
                ('total_days_of_season', models.IntegerField(default=0)),
                ('number_of_days_participated', models.IntegerField(default=0)),
                ('consecutive_streak', models.IntegerField(default=0)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
