# Generated by Django 4.1 on 2022-09-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_ques_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ques_list',
            name='ques',
            field=models.CharField(max_length=550),
        ),
    ]
