# Generated by Django 4.1 on 2022-09-26 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_ques_list_ques'),
    ]

    operations = [
        migrations.CreateModel(
            name='player_stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(max_length=10)),
                ('alloted_qid', models.CharField(max_length=100)),
                ('groupid', models.CharField(max_length=10)),
                ('gameid', models.CharField(max_length=10)),
                ('user_days_score', models.IntegerField(default=10)),
                ('user_total_score', models.IntegerField(default=0)),
                ('marks_of_days_quiz', models.IntegerField(default=0)),
                ('total_marks_of_quiz', models.IntegerField(default=0)),
                ('accuracy', models.IntegerField(default=0)),
                ('total_days_participated', models.IntegerField(default=0)),
                ('consecutive_streak', models.IntegerField(default=0)),
                ('streak_counter', models.IntegerField(default=0)),
                ('date_of_participation', models.DateField(default=datetime.date(2022, 9, 26))),
            ],
        ),
    ]
