# Generated by Django 4.1 on 2022-09-26 14:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_player_stats'),
    ]

    operations = [
        migrations.CreateModel(
            name='GU_Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Player_name', models.CharField(default='guest', max_length=100)),
                ('day_score', models.IntegerField(default=0)),
                ('attemt', models.IntegerField(default=0)),
                ('season_score', models.IntegerField(default=0)),
                ('attended', models.BooleanField(default=False)),
                ('accuracy', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=0)),
                ('percentile', models.FloatField(default=0)),
                ('total_days_of_season', models.IntegerField(default=0)),
                ('number_of_days_participated', models.IntegerField(default=0)),
                ('consecutive_streak', models.IntegerField(default=0)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
