# Generated by Django 4.0.7 on 2022-09-28 07:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_question_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_bank',
            name='date_of_ques_in_quiz',
            field=models.DateField(default='2022-12-01'),
        ),
        migrations.AlterField(
            model_name='my_score',
            name='played_dt',
            field=models.DateField(verbose_name=datetime.date(2022, 9, 28)),
        ),
        migrations.AlterField(
            model_name='player_score',
            name='played_dt',
            field=models.DateField(verbose_name=datetime.date(2022, 9, 28)),
        ),
        migrations.AlterField(
            model_name='player_stats',
            name='date_of_participation',
            field=models.DateField(default=datetime.date(2022, 9, 28)),
        ),
        migrations.AlterField(
            model_name='user_stats',
            name='date_of_participation',
            field=models.DateField(default=datetime.date(2022, 9, 28)),
        ),
    ]
