# Generated by Django 4.0.7 on 2022-09-29 11:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_question_bank_date_of_ques_in_quiz_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='select_winners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner_ids', models.CharField(max_length=250)),
                ('game_id', models.CharField(max_length=10)),
                ('winner_category', models.CharField(max_length=10)),
                ('winner_selection_date', models.DateField(default='2022,12-24')),
                ('winner_selection_range_from', models.DateField(default='2022-12-34')),
                ('winner_selection_range_to', models.DateField(default='2022-12-34')),
            ],
        ),
        migrations.AlterField(
            model_name='my_score',
            name='played_dt',
            field=models.DateField(verbose_name=datetime.date(2022, 9, 29)),
        ),
        migrations.AlterField(
            model_name='player_score',
            name='played_dt',
            field=models.DateField(verbose_name=datetime.date(2022, 9, 29)),
        ),
        migrations.AlterField(
            model_name='player_stats',
            name='date_of_participation',
            field=models.DateField(default=datetime.date(2022, 9, 29)),
        ),
        migrations.AlterField(
            model_name='user_stats',
            name='date_of_participation',
            field=models.DateField(default=datetime.date(2022, 9, 29)),
        ),
    ]
