# Generated by Django 4.0.7 on 2022-10-01 04:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_select_winners_alter_my_score_played_dt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_stats',
            name='player_name',
            field=models.CharField(default='Not Available', max_length=50),
        ),
        migrations.AddField(
            model_name='player_stats',
            name='profile_photo_url',
            field=models.CharField(default='Not Available', max_length=100),
        ),
        migrations.AlterField(
            model_name='my_score',
            name='played_dt',
            field=models.DateField(verbose_name=datetime.date(2022, 10, 1)),
        ),
        migrations.AlterField(
            model_name='player_score',
            name='played_dt',
            field=models.DateField(verbose_name=datetime.date(2022, 10, 1)),
        ),
        migrations.AlterField(
            model_name='player_stats',
            name='date_of_participation',
            field=models.DateField(default=datetime.date(2022, 10, 1)),
        ),
        migrations.AlterField(
            model_name='user_stats',
            name='date_of_participation',
            field=models.DateField(default=datetime.date(2022, 10, 1)),
        ),
    ]
